Example endpoint returning the buildings.
In this example the specification is taken from external YAML file
---
parameters:
  - name: Building JSON
    in: path
    type: json
    enum: ['building', 'wayPoint', 'connector', 'classroom', 'floor', 'group', 'office','teacher']
    required: true
    default: all
definitions:
  Building:
    type: object
    properties:
      name:
        type: string
  Waypoint:
    type: object
    properties:
      Waypoint_name:
        type: string
  Connector:
    type: object
    properties:
      Connector_name:
        type: string
responses:
  200:
    description: A list of buildings.
    schema:
      $ref: '#/definitions/Building'
    examples:
      buildings: ['FII', 'C3', 'C2']